Repository Silver15987/pomo-bot, pull requests merged in 2025-06, with the labels that each got.

#12 fix: task duration and stats tracking
  config/bot-config.json
  db/tasks.js
  handlers/interactionHandler.js
  handlers/taskPromptHandler.js
Labels: bug, enhancement

#15 i cant be bothered to write an actual commit now. SCREW AI
  db/tasks.js
  handlers/interactionHandler.js
  handlers/taskPromptHandler.js
  handlers/voiceHandler.js
Labels: stupidity

#20 fix: add null check for `oldState.channel`
  handlers/voiceHandler.js
Labels: bug
